### ISSUE TITLE
Harmony Remote Dim/Brighten Buttons not working properly

### ISSUE THREAD

**Issue by Astroman** [FlyingDiver/Indigo-lifx-bridge#2]
Hi again Joe, Thanks so much for getting the plugin working with the Aeotec LED Strip. I know it took a lot of effort and I appreciate it. Hope you don't mind just a little more discussion on the brightness control issue.

You are definitely sending the correct dimming commands based on the absolute brightness requests being sent by the Harmony Hub. What I don't see though is how Harmony determines the current brightness level from which to compute the incremental change. Does it query your plugin for the current brightness? Although I don't see that in the log, I don't see how else this could work.

Watching the behavior of the Harmony app brightness, I can see what the harmony hub thinks it is set at. For example, when I dim with the remote, I see the app brightness go down but then, about a second later, it goes back up. I suspect the values it is getting from the plugin are out of sync somehow. Maybe it's first assuming a percentage drop based on the command and then querying the brightness from the plugin before the value has been updated. This is speculation but it is clear that the problem is caused by the plugin and Harmony app brightness levels being out of sync.

I also don't see a change in the brightness level based on changes made by Indigo directly but this is understandable and should only result in a one time incorrect change until the values get in sync.

**Comment by FlyingDiver** [comment]
When the Harmony app starts up, I do see a series of GetLightColor messages (and other ones) that make me think it's syncing up the values at that time.  Set the plugin logging to debug and open the app and you should see them all.

For something like this sequence, you can see that the Harmony app (and the plugin) are dealing with absolute brightness levels.  It's Indigo itself that is doing the delta between the current level and the commanded level to issue the DIM or BRIGHTEN command.

```
   LIFX Bridge Debug               LightSetColor command is for device: Family Room Light, payload = [('Color', (0, 0, 39476, 3003)), ('Duration', 1000)]
   LIFX Bridge                     setDeviceColor for 1525081080: hue = 0, saturation = 0, brightness = 39476, color = 3003
   LIFX Bridge                     setDeviceColor: 1525081080 to 60 (non-RGB)
   Sent X10                        "Family Room Light" brighten by 10
   
   LIFX Bridge Debug               LightSetColor command is for device: Family Room Light, payload = [('Color', (0, 0, 26317, 3003)), ('Duration', 1000)]
   LIFX Bridge                     setDeviceColor for 1525081080: hue = 0, saturation = 0, brightness = 26317, color = 3003
   LIFX Bridge                     setDeviceColor: 1525081080 to 40 (non-RGB)
   Sent X10                        "Family Room Light" dim by 20
```

What the plugin doesn't do, and maybe should, is watch for changes in all the managed devices (from Indigo) and send out status messages reporting those changes. I think that's possible in the protocol, but I don't know if any other clients do it.

**Comment by Astroman** [comment]
I think Indigo is changing the brightness correctly based on the requests. The problem is that the requests are wrong since Harmony has an incorrect initial value.

Looking at the detailed log, I see that Harmony is determining the new brightness value in SetDeviceColor and then using GetDeviceColor to determine the actual brightness. Very odd since it would need to get the current brightness in order to determine what new brightness to send based on an incremental adjustment. It doesn't even seem to be using the retrieved brightness to determine the starting point for the next change; I don't know where it is getting the initial value.

Assuming Harmony would use your reported value for its calculation, your idea would solve this problem and also keep Harmony up with changes in brightness made asynchronously by Indigo. However, it would not be necessary if Harmony simply queried for the current brightness before computing the incremental change. Maybe it's assuming all changes would be reported asynchronously and is just making the query to confirm the change it just made. Or maybe this is just a bug and they really intended to query the current value before computing the new one. Hard to tell.

**Comment by FlyingDiver** [comment]
I'll take a look at the startup sequence and see if maybe I'm not reporting an initial value correctly.

Or it might just be the hub screwing up.  ;)

**Comment by Astroman** [comment]
Just to be clear, I don't think it's a problem with the startup sequence. Every time an incremental change in brightness is executed by the Harmony remote, the numbers get out of sync, possibly because they are updating the brightness at the wrong point in the sequence.

**Comment by FlyingDiver** [comment]
You're using a hard button remote to do that?  With the rocker switches?

**Comment by Astroman** [comment]
Whoops. Yes, I tried to make that clear by calling it the Harmony remote device but I guess I didn't make it clear enough. You must have thought I was off my "rocker". :)

This never used to work at all, sending all kinds of weird levels. Now it's very close to working.

**Comment by Astroman** [comment]
BTW, I realize we had a thread on this a year or so ago, but the situation has changed a lot since then, possibly due to your recent work on the brightness controls.

**Comment by FlyingDiver** [comment]
I guess this is still an issue?

**Comment by Astroman** [comment]
Yep. Please let me know if there is anything I can do to help.

**Comment by FlyingDiver** [comment]
Can you create a new debug log file with the sequences when this happens?  I'll take a look at it again.

**Comment by Astroman** [comment]
OK, here is an example sequence. Started with on at 100 brightness. Pressed dim, brighten, dim, brighten, dim, dim. First 5 dims and brightens made it go up and down by 80-100%. Final dim actually brightened it to 90.
[Harmony_Dimming_Log.txt](https://github.com/FlyingDiver/Indigo-lifx-bridge/files/2586863/Harmony_Dimming_Log.txt)

**Comment by FlyingDiver** [comment]
I don't think it's in any way related, but could you do me a favor and do the same sequence with the Harmony Hub plugin disabled?

**Comment by FlyingDiver** [comment]
Also, do you have any actual LIFX devices?

**Comment by Astroman** [comment]
No LIFX devices.
Here is the log with the plugin disabled. Results are not repeatable, I think since it depends what was previously done with the device. Note that the dimming and brightening factors change by 10 each time and the last extra dim brightens instead of dimming.
[Harmony_Dimming_plugin_disabled_Log.txt](https://github.com/FlyingDiver/Indigo-lifx-bridge/files/2586978/Harmony_Dimming_plugin_disabled_Log.txt)

**Comment by FlyingDiver** [comment]
At this point, I'm guessing the Harmony is expecting a status report from the LIFX device with the current brightness level, and since it's not getting one it's incrementing the dim request.

For instance, start at 100.
Send dim (by 10), expect 90 and not get it so on next keypress dim by 20.

**Comment by FlyingDiver** [comment]
Try this version and see what happens.  I'm forcing a status reply after every SetDeviceColor message, even if not requested.  It's possible it's actually doing the request and the underlying library isn't decoding it properly.

https://github.com/FlyingDiver/Indigo-lifx-bridge/releases/tag/7.1.3

**Comment by Astroman** [comment]
Fails in a similar way as the previous version. Different values but the other version also was somewhat random in the specific values so that might not be significant.

**Comment by FlyingDiver** [comment]
OK, I'm going to have to get my one LIFX bulb out of storage and see if it works properly with it.

**Comment by FlyingDiver** [comment]
Not to be fixed.
