### ISSUE TITLE
problem handling non-breaking space in device name

### ISSUE THREAD

**Issue by dduff617** [FlyingDiver/Indigo-lifx-bridge#3]
i'm getting a repeating error message, as follows:

```
   LIFX Bridge Error               Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 94, in runConcurrentThread
  File "plugin.py", line 724, in lifxRespond
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 0: ordinal not in range(128)

   LIFX Bridge Error               plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
```

I have some devices with the non-breaking space (on mac, typed as option-space) in their names to cause them to appear at top of sorted list.    This seems to be causing problems.   I presume the same problem might occur for other non-standard characters in Indigo device names.

I get the above recurring error message that appears spontaneously.  Basically the same error message also appears if I attempt "list devices".

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-lifx-bridge/releases/tag/7.1.1

**Comment by dduff617** [comment]
This seems to have fixed the problem.   I'm not seeing the error msg and the "list devices" command from the plugin menu now works.
