### ISSUE TITLE
character encoding error (again)

### ISSUE THREAD

**Issue by dduff617** [FlyingDiver/Indigo-lifx-bridge#4]
Seems very similar to a bug I reported earlier this year (and was fixed quickly in 7.1.1), but now showing up at a different location. 

Attempting "Print Device List to Log", i see this:
   LIFX Bridge                     Indigo DevID      LIFX Address         Indigo Name (alias)           
   LIFX Bridge Error               Error in plugin execution MenuAction:

Traceback (most recent call last):
  File "plugin.py", line 281, in listDevices
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 0: ordinal not in range(128)

**Comment by FlyingDiver** [comment]
Try:  https://github.com/FlyingDiver/Indigo-lifx-bridge/releases/tag/7.1.2
