### ISSUE TITLE
LIFX Bridge: issue with device names containing accents

### ISSUE THREAD

**Issue by jomisaji** [FlyingDiver/Indigo-lifx-bridge#5]
If the Indigo name of a device to be published contains accents and no accent-free alternate name is provided, Harmony won't find it, and no warning or error is given.

**Comment by FlyingDiver** [comment]
Will look into this as soon as I can.

**Comment by FlyingDiver** [comment]
Since not recognizing device names with unicode characters in them is a Harmony problem, do you think that automatically creating an ASCII only alternate name would be a reasonable solution?

**Comment by FlyingDiver** [comment]
Best solution would be to report an error when trying to add a device to the published list if the name is unicode without an ascii altName.

**Comment by FlyingDiver** [comment]
Hack fix in 7.1.4.  Any non-ascii characters are in the device name replaced with "_" then that is forced into the alias.
